version: 0.2

env:
  variables:
    S3_BUCKET_NAME: ""
    PROJECT_ANGULAR_NAME: "say-is-ok"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing...
      - npm install --prefix ./${PROJECT_ANGULAR_NAME}

  build:
    commands:
      - npm run build --prefix ./${PROJECT_ANGULAR_NAME}
  post_build:
    commands:
      - echo syncing files with s3://${S3_BUCKET_NAME}...
      - aws s3 sync ./${PROJECT_ANGULAR_NAME}/dist/${PROJECT_ANGULAR_NAME} s3://${S3_BUCKET_NAME} --delete
