Description: Create notification for buckets

AWSTemplateFormatVersion: 2010-09-09

Parameters:
  TargetBucketName:
    Type: String

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic

  SNSTopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Id: S3Publish
        Version: 2012-10-17
        Statement:
          - Sid: Statement-id
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: "sns:Publish"
            Resource: !Ref SNSTopic
            Condition:
              ArnLike:
                "aws:SourceArn": !Sub "arn:aws:s3:::${TargetBucketName}"
      Topics:
        - !Ref SNSTopic

Outputs:
  S3SNSTopicArn:
    Description: The SNS topic to objects created at bucket
    Value: !Ref SNSTopic
