AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  test-sam

  Sample SAM Template for test-sam

Parameters:
  S3SNSTopic:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ResizeImage:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: resize-image/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref S3SNSTopic
            SqsSubscription: true

Outputs:
  ResizeImage:
    Description: "Lambda Function ARN"
    Value: !GetAtt ResizeImage.Arn
  ResizeImageIamRole:
    Description: "Implicit IAM Role created for the function"
    Value: !GetAtt ResizeImageRole.Arn
