AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  test-sam

  Sample SAM Template for test-sam

Parameters:
  S3SNSTopic:
    Type: String
  S3StorageBucketName:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  # LambdaRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: 2012-10-17
  #       Statement:
  #         - Action:
  #             - sts:AssumeRole
  #           Effect: Allow
  #           Principal:
  #             Service:
  #               - lambda.amazonaws.com

  # Policy:
  #   Type: "AWS::IAM::Policy"
  #   Properties:
  #     PolicyName: !Sub "${AWS::StackName}-lambda-policy-sqs"
  #     Roles:
  #       - !Ref ResizeImageRole
  #     PolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Sid: SqsEvents
  #           Effect: "Allow"
  #           Action:
  #             - "sqs:SendMessage"
  #             - "sqs:DeleteMessage"
  #             - "sqs:ChangeMessageVisibility"
  #             - "sqs:ReceiveMessage"
  #             - "sqs:TagQueue"
  #             - "sqs:UntagQueue"
  #             - "sqs:PurgeQueue"
  #           Resource: !Sub
  #             - "arn:aws:sqs:${region}:${account}:${destSqs}"
  #             - region: !Ref "AWS::Region"
  #               account: !Ref "AWS::AccountId"
  #               destSqs: !GetAtt [ResizeImage, DestinationQueue]

  ResizeImage:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: resize-image/
      Handler: app.handler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref S3SNSTopic
            SqsSubscription: true

  PolicyS3:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: !Sub "${AWS::StackName}-lambda-policy-s3"
      Roles:
        - !Ref ResizeImageRole # When the Role property of an AWS::Serverless::Function is not specified, AWS SAM generates an AWS::IAM::Role AWS CloudFormation resource: <function‑LogicalId>Role
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: S3Events
            Effect: Allow
            Action:
              - "s3:*"
              - "s3-object-lambda:*"
            Resource: !Sub "arn:aws:s3:::${S3StorageBucketName}*"

Outputs:
  ResizeImageFunctionIamRole:
    Description: "Implicit IAM Role created for ResizeImage function"
    Value: !GetAtt ResizeImageRole.Arn
  ResizeImageFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt ResizeImage.Arn
