AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  test-sam

  Sample SAM Template for test-sam

Parameters:
  S3SNSTopic:
    Type: String
  S3StorageBucketName:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
       Policies:
        - PolicyName: !Sub "${AWS::StackName}-lambda-role"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:*"
                  - "s3-object-lambda:*"
                Resource: !Sub "arn:aws:s3:::${S3StorageBucketName}*"


  ResizeImage:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Role: !Ref LambdaRole
      CodeUri: resize-image/
      Handler: app.handler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref S3SNSTopic
            SqsSubscription: true

Outputs:
  ResizeImage:
    Description: "Lambda Function ARN"
    Value: !GetAtt ResizeImage.Arn
  ResizeImageIamRole:
    Description: "IAM Role created for the function"
    Value: !Ref LambdaRole
